import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, GitBranch, Pause, Play, RefreshCw, ShieldCheck, Target, Workflow, XCircle } from "lucide-react";
import { getFriendlyErrorMessage } from "../../api/client";
import { officeApi, type OfficeBrainMissionGraph } from "../../api/office";
import { useLuluApp } from "../../api/LuluAppContext";
import { workforceControlApi, type AutonomyIncident, type AutonomyReadiness, type AutonomyRollout, type BusinessGoal, type DecisionRequest, type Playbook, type WorkflowGraph } from "../../api/workforce-control";
import { useLocation, useNavigate } from "react-router-dom";
import "./workforce-control-center-completion.css";

type Panel = "overview" | "workflow" | "goals" | "playbooks" | "autonomy" | "decisions" | "incidents";

const workflowStatuses = ["CREATED", "PLANNING", "RUNNING", "WAITING_FOR_APPROVAL", "WAITING_FOR_USER_INPUT", "WAITING_FOR_PROVIDER", "WAITING_FOR_RECONCILIATION", "VERIFYING", "COMPLETED", "FAILED", "CANCELLED"];
const autonomyModes: AutonomyRollout["mode"][] = ["DISABLED", "SHADOW", "RECOMMEND_ONLY", "AUTONOMOUS_WITHIN_POLICY"];

function humanize(value: unknown) {
  return String(value ?? "—").replaceAll("_", " ").toLowerCase().replace(/(^|\s)\S/g, (letter) => letter.toUpperCase());
}

function when(value: string | null | undefined) {
  return value ? new Date(value).toLocaleString([], { dateStyle: "short", timeStyle: "short" }) : "—";
}

function Badge({ value, tone = "neutral" }: { value: unknown; tone?: "neutral" | "good" | "attention" | "critical" }) {
  return <span className={`lulu-completion__badge lulu-completion__badge--${tone}`}>{humanize(value)}</span>;
}

function PanelCard({ title, eyebrow, children, actions }: { title: string; eyebrow?: string; children: React.ReactNode; actions?: React.ReactNode }) {
  return <section className="lulu-completion__card"><header className="lulu-completion__card-header"><div>{eyebrow && <span className="lulu-completion__eyebrow">{eyebrow}</span>}<h3>{title}</h3></div>{actions}</header>{children}</section>;
}

function StateList({ items, empty = "No persisted data is available." }: { items: Array<{ label: string; value: React.ReactNode }>; empty?: string }) {
  if (items.length === 0) return <p className="lulu-completion__muted">{empty}</p>;
  return <dl className="lulu-completion__facts">{items.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>;
}

function WorkflowInspector({ workspaceId, initialWorkflowId }: { workspaceId: string; initialWorkflowId: string | null }) {
  const [workflowId, setWorkflowId] = useState(initialWorkflowId ?? "");
  const [graph, setGraph] = useState<WorkflowGraph | null>(null);
  const [missionGraph, setMissionGraph] = useState<OfficeBrainMissionGraph | null>(null);
  const [loading, setLoading] = useState(Boolean(initialWorkflowId));
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (id = workflowId) => {
    if (!id.trim()) return;
    setLoading(true); setError(null);
    try {
      const response = await workforceControlApi.workflow(workspaceId, id.trim());
      setGraph(response.data);
      const missionId = response.data.missions[0]?.id;
      setMissionGraph(missionId ? (await officeApi.brainMissionGraph(workspaceId, missionId)).data : null);
    } catch (loadError) {
      setGraph(null); setMissionGraph(null); setError(getFriendlyErrorMessage(loadError));
    } finally { setLoading(false); }
  }, [workspaceId, workflowId]);

  useEffect(() => { if (initialWorkflowId) void load(initialWorkflowId); }, [initialWorkflowId, load]);

  const activeRevision = graph?.planRevisions.at(-1)?.revision ?? graph?.missions.at(-1)?.planRevision ?? null;
  const completedTasks = graph?.tasks.filter((task) => task.status === "COMPLETED").length ?? 0;
  const verificationStates = graph?.toolInvocations.map((tool) => tool.verification?.status ?? tool.status).filter(Boolean) ?? [];
  const taskDependencies = useMemo(() => new Map((missionGraph?.dependencies ?? []).map((dependency) => [dependency.taskId, dependency])), [missionGraph]);

  return <div className="lulu-completion__stack">
    <PanelCard title="Workflow Inspector" eyebrow="Business lifecycle">
      <form className="lulu-completion__lookup" onSubmit={(event) => { event.preventDefault(); void load(); }}>
        <label htmlFor="workflow-id">Workflow ID</label>
        <input id="workflow-id" value={workflowId} onChange={(event) => setWorkflowId(event.target.value)} placeholder="Paste a persisted workflow ID" />
        <button type="submit" className="lulu-completion__button lulu-completion__button--primary" disabled={loading || !workflowId.trim()}><Workflow size={15} />Inspect</button>
      </form>
      {loading && <div className="lulu-completion__state"><RefreshCw className="lulu-completion__spin" size={18} />Loading canonical workflow state…</div>}
      {error && <div className="lulu-completion__error" role="alert"><AlertTriangle size={16} />{error}</div>}
      {!loading && !graph && !error && <div className="lulu-completion__empty"><GitBranch size={20} /><p>Open a workflow from a notification or paste its ID to inspect its persisted lifecycle.</p></div>}
      {graph && <>
        <div className="lulu-completion__workflow-summary"><div><span className="lulu-completion__eyebrow">What was Lulu asked to do?</span><h4>{graph.workflow.objective}</h4><p>{humanize(graph.workflow.sourceType)} · {humanize(graph.workflow.workflowType)}</p></div><Badge value={graph.workflow.status} tone={graph.workflow.status === "FAILED" ? "critical" : graph.workflow.status === "COMPLETED" ? "good" : "attention"} /></div>
        <div className="lulu-completion__lifecycle">{["SOURCE", "INTENT", "CONTEXT", "PLAN", "TASK DAG", "AGENTS", "TOOLS", "POLICY / APPROVAL", "EXECUTION", "VERIFICATION", "RECOVERY", "BUSINESS OUTCOME"].map((stage, index) => { const evidence = [graph.workflow.sourceType, graph.intents.length, Object.keys(graph.workflow.metadata ?? {}).length, activeRevision ?? "—", `${completedTasks}/${graph.tasks.length}`, graph.agentRuns.length, graph.toolInvocations.length, graph.approvals.length, graph.agentSteps.length, verificationStates.length, graph.workflow.status === "WAITING_FOR_RECONCILIATION" ? "waiting" : "—", graph.workflow.status === "COMPLETED" ? "recorded" : "pending"][index]; return <div key={stage} className="lulu-completion__lifecycle-node"><span>{stage}</span><strong>{String(evidence)}</strong></div>; })}</div>
        <div className="lulu-completion__technical-grid"><StateList items={[{ label: "Workflow", value: graph.workflow.id }, { label: "Current stage", value: humanize(graph.workflow.currentStage) }, { label: "Created", value: when(graph.workflow.createdAt) }, { label: "Updated", value: when(graph.workflow.updatedAt) }]} /><StateList items={[{ label: "Intent", value: graph.intents[0] ? `${humanize(graph.intents[0].intentType)} · ${humanize(graph.intents[0].status)}` : "No persisted intent" }, { label: "Plan revision", value: activeRevision ?? "No plan revision" }, { label: "Approvals", value: graph.approvals.length }, { label: "Action packets", value: graph.actionPackets.length }]} /></div>
      </>}
    </PanelCard>
    {graph && <>
      <PanelCard title="Task DAG" eyebrow="Technical view"><div className="lulu-completion__task-grid">{graph.tasks.map((task) => { const dependency = taskDependencies.get(task.id); return <article className="lulu-completion__task" key={task.id}><div className="lulu-completion__task-heading"><strong>{task.title}</strong><Badge value={task.status} tone={task.status === "FAILED" ? "critical" : task.status === "COMPLETED" ? "good" : task.waitState ? "attention" : "neutral"} /></div><p>{task.objective}</p><small>{task.domain ?? "General"} · {dependency ? `depends on ${dependency.title}` : "no dependency recorded"}</small>{task.waitState && <div className="lulu-completion__task-wait">Waiting: {humanize(task.waitState)}</div>}</article>; })}{graph.tasks.length === 0 && <p className="lulu-completion__muted">No task DAG is persisted for this workflow.</p>}</div></PanelCard>
      <div className="lulu-completion__two-column"><PanelCard title="Plan revisions" eyebrow="Planner history"><div className="lulu-completion__revision-list">{graph.planRevisions.map((revision) => <article key={revision.id}><div><strong>Plan v{revision.revision}</strong><small>{when(revision.createdAt)} · {revision.planningReason || "No reason recorded"}</small></div><Badge value={revision.status} tone={revision.revision === activeRevision ? "good" : "neutral"} /></article>)}{graph.planRevisions.length === 0 && <p className="lulu-completion__muted">No persisted plan revisions are available.</p>}</div></PanelCard><PanelCard title="Tools, approval and verification" eyebrow="Governed execution"><div className="lulu-completion__table">{graph.toolInvocations.map((tool) => <div key={tool.id}><span><strong>{tool.toolId}</strong><small>v{tool.toolVersion} · {humanize(tool.operationType)}</small></span><Badge value={tool.verification?.status ?? tool.status} tone={tool.verification?.status === "VERIFIED" ? "good" : "attention"} /></div>)}{graph.toolInvocations.length === 0 && <p className="lulu-completion__muted">No tool invocation is linked to this workflow.</p>}</div></PanelCard></div>
    </>}
  </div>;
}

function GoalsPanel({ workspaceId }: { workspaceId: string }) {
  const [goals, setGoals] = useState<BusinessGoal[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); void workforceControlApi.goals(workspaceId).then((response) => { if (active) setGoals(response.data.items); }).catch((loadError) => { if (active) setError(getFriendlyErrorMessage(loadError)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [workspaceId]);
  return <PanelCard title="Goals and portfolio" eyebrow="Goal → Mission → Workflow"><p className="lulu-completion__panel-intro">Goals remain the business authority. This view links their current evidence and autonomy mode without inventing progress.</p>{loading && <div className="lulu-completion__state"><RefreshCw className="lulu-completion__spin" size={18} />Loading goals…</div>}{error && <div className="lulu-completion__error"><AlertTriangle size={16} />{error}</div>}<div className="lulu-completion__goal-grid">{goals.map((goal) => <article key={goal.id} className="lulu-completion__goal"><div className="lulu-completion__task-heading"><strong>{goal.title}</strong><Badge value={goal.status} tone={goal.status === "ACTIVE" ? "good" : "neutral"} /></div><p>{goal.description || "No description recorded."}</p><div className="lulu-completion__goal-values"><span>Current <b>{goal.currentValue ?? "—"}</b></span><span>Target <b>{goal.targetValue}</b></span></div><small>{goal.metricName} · {humanize(goal.autonomyMode)} · updated {when(goal.updatedAt)}</small></article>)}{!loading && goals.length === 0 && <div className="lulu-completion__empty"><Target size={20} /><p>No business goals are available in this workspace.</p></div>}</div></PanelCard>;
}

function PlaybooksPanel({ workspaceId }: { workspaceId: string }) {
  const [playbooks, setPlaybooks] = useState<Playbook[]>([]); const [selected, setSelected] = useState<Playbook | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const response = await workforceControlApi.playbooks(workspaceId); setPlaybooks(response.data.items); } catch (loadError) { setError(getFriendlyErrorMessage(loadError)); } }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  const changeStatus = async (action: "activate" | "pause") => { if (!selected) return; setBusy(true); setError(null); try { const response = action === "activate" ? await workforceControlApi.activatePlaybook(workspaceId, selected.id) : await workforceControlApi.pausePlaybook(workspaceId, selected.id); setSelected(response.data); setPlaybooks((current) => current.map((item) => item.id === response.data.id ? response.data : item)); } catch (actionError) { setError(getFriendlyErrorMessage(actionError)); } finally { setBusy(false); } };
  return <div className="lulu-completion__two-column"><PanelCard title="Playbooks" eyebrow="Operational procedures"><p className="lulu-completion__panel-intro">Active versions are immutable. Editing must create a new draft/version before validation and activation.</p>{error && <div className="lulu-completion__error"><AlertTriangle size={16} />{error}</div>}<div className="lulu-completion__list">{playbooks.map((playbook) => <button type="button" key={playbook.id} className={`lulu-completion__list-item${selected?.id === playbook.id ? " is-selected" : ""}`} onClick={() => { setSelected(playbook); setError(null); }}><span><strong>{playbook.name}</strong><small>{playbook.playbookKey} · v{playbook.version} · {humanize(playbook.domain)}</small></span><Badge value={playbook.status} tone={playbook.status === "ACTIVE" ? "good" : playbook.status === "DRAFT" ? "attention" : "neutral"} /><ChevronRight size={15} /></button>)}{playbooks.length === 0 && <p className="lulu-completion__muted">No workspace playbooks are available.</p>}</div></PanelCard>{selected ? <PanelCard title={selected.name} eyebrow={`Playbook v${selected.version}`} actions={<button type="button" className="lulu-completion__icon-button" onClick={() => setSelected(null)} aria-label="Close playbook"><XCircle size={17} /></button>}><StateList items={[{ label: "Status", value: <Badge value={selected.status} /> }, { label: "Domain", value: humanize(selected.domain) }, { label: "Autonomy", value: humanize(selected.autonomyMode) }, { label: "Steps", value: selected.steps.length }]} /><div className="lulu-completion__step-list">{selected.steps.map((step) => <article key={step.id}><strong>{step.position + 1}. {step.title}</strong><small>{step.objective || "No objective recorded."}</small><span>{humanize(step.optionality)} · {humanize(step.responsibility)} · {step.requiredTools.length} required tools</span></article>)}</div><div className="lulu-completion__action-row">{selected.status === "DRAFT" || selected.status === "PAUSED" ? <button type="button" className="lulu-completion__button lulu-completion__button--primary" onClick={() => void changeStatus("activate")} disabled={busy}><Play size={14} />Activate validated version</button> : null}{selected.status === "ACTIVE" && <button type="button" className="lulu-completion__button" onClick={() => void changeStatus("pause")} disabled={busy}><Pause size={14} />Pause</button>}</div></PanelCard> : <PanelCard title="Select a playbook" eyebrow="Version-safe editing"><div className="lulu-completion__empty"><GitBranch size={20} /><p>Choose a playbook to inspect its steps, autonomy mode, approvals and version state.</p></div></PanelCard>}</div>;
}

function AutonomyPanel({ workspaceId }: { workspaceId: string }) {
  const [readiness, setReadiness] = useState<AutonomyReadiness | null>(null); const [rollouts, setRollouts] = useState<AutonomyRollout[]>([]); const [incidents, setIncidents] = useState<AutonomyIncident[]>([]); const [mode, setMode] = useState<AutonomyRollout["mode"]>("RECOMMEND_ONLY"); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const results = await Promise.allSettled([workforceControlApi.autonomyReadiness(workspaceId), workforceControlApi.autonomyRollouts(workspaceId), workforceControlApi.autonomyIncidents(workspaceId)]); const [readinessResult, rolloutResult, incidentResult] = results; if (readinessResult.status === "fulfilled") setReadiness(readinessResult.value.data); if (rolloutResult.status === "fulfilled") { setRollouts(rolloutResult.value.data.items); if (rolloutResult.value.data.items[0]) setMode(rolloutResult.value.data.items[0].mode); } if (incidentResult.status === "fulfilled") setIncidents(incidentResult.value.data.items); const failure = results.find((result) => result.status === "rejected"); if (failure && failure.status === "rejected") setError(getFriendlyErrorMessage(failure.reason)); }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  const updateMode = async () => { setBusy(true); setError(null); try { const response = await workforceControlApi.setRollout(workspaceId, { scopeType: "WORKSPACE", scopeKey: "", mode, gateConfig: {}, status: "ACTIVE" }); setRollouts((current) => [response.data, ...current.filter((item) => !(item.scopeType === "WORKSPACE" && item.scopeKey === ""))]); } catch (actionError) { setError(getFriendlyErrorMessage(actionError)); } finally { setBusy(false); } };
  const mitigate = async (incident: AutonomyIncident) => { try { await workforceControlApi.mitigateIncident(workspaceId, incident.id, "RESOLVED"); await load(); } catch (actionError) { setError(getFriendlyErrorMessage(actionError)); } };
  const gates = readiness ? Object.entries(readiness).filter(([key]) => key !== "reasons") as Array<[string, unknown]> : [];
  return <div className="lulu-completion__two-column"><PanelCard title="Autonomy management" eyebrow="Phase 9 rollout"><p className="lulu-completion__panel-intro">Modes are server-controlled and remain subordinate to policy, approvals and verification. No unrestricted mode is exposed.</p>{error && <div className="lulu-completion__error"><AlertTriangle size={16} />{error}</div>}<div className="lulu-completion__readiness">{gates.map(([key, value]) => <div key={key}><span>{humanize(key)}</span><Badge value={value} tone={value === "READY" ? "good" : value === "BLOCKED" ? "critical" : "attention"} /></div>)}</div>{readiness?.reasons.map((reason) => <p className="lulu-completion__reason" key={reason}><AlertTriangle size={14} />{reason}</p>)}<div className="lulu-completion__rollout-editor"><label htmlFor="workspace-autonomy-mode">Workspace mode</label><select id="workspace-autonomy-mode" value={mode} onChange={(event) => setMode(event.target.value as AutonomyRollout["mode"])}>{autonomyModes.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select><button type="button" className="lulu-completion__button lulu-completion__button--primary" onClick={() => void updateMode()} disabled={busy}><ShieldCheck size={14} />Save governed mode</button></div></PanelCard><PanelCard title="Incidents" eyebrow="Safety lifecycle"><div className="lulu-completion__list">{incidents.map((incident) => <div className="lulu-completion__list-item" key={incident.id}><span><strong>{humanize(incident.incidentType)}</strong><small>{humanize(incident.severity)} · {when(incident.createdAt)} · {humanize(incident.status)}</small></span>{["OPEN", "MITIGATED"].includes(incident.status) ? <button type="button" className="lulu-completion__button" onClick={() => void mitigate(incident)}>Resolve</button> : <Badge value={incident.status} tone="good" />}</div>)}{incidents.length === 0 && <div className="lulu-completion__empty"><CheckCircle2 size={20} /><p>No autonomy incidents are currently recorded.</p></div>}</div></PanelCard></div>;
}

function DecisionsPanel({ workspaceId }: { workspaceId: string }) {
  const [requests, setRequests] = useState<DecisionRequest[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  useEffect(() => { let active = true; void workforceControlApi.decisionRequests(workspaceId).then((response) => { if (active) setRequests(response.data.items); }).catch((loadError) => { if (active) setError(getFriendlyErrorMessage(loadError)); }); return () => { active = false; }; }, [workspaceId]);
  const resolve = async (request: DecisionRequest, optionId: string) => { setBusy(request.id); setError(null); try { await workforceControlApi.resolveDecision(workspaceId, request.id, optionId, "Resolved from the Workforce Control Center."); setRequests((current) => current.map((item) => item.id === request.id ? { ...item, status: "RESOLVED" } : item)); } catch (actionError) { setError(getFriendlyErrorMessage(actionError)); } finally { setBusy(null); } };
  return <PanelCard title="Executive decisions" eyebrow="Human decision boundary"><p className="lulu-completion__panel-intro">Decision requests are resolved through the canonical backend API. A recommendation never becomes authorization by itself.</p>{error && <div className="lulu-completion__error"><AlertTriangle size={16} />{error}</div>}<div className="lulu-completion__decision-list">{requests.map((request) => <article key={request.id}><div className="lulu-completion__task-heading"><div><strong>{request.title}</strong><p>{request.question}</p></div><Badge value={request.status} tone={request.status === "PENDING" ? "attention" : "good"} /></div>{request.status === "PENDING" && <div className="lulu-completion__action-row">{request.options.map((option) => <button type="button" className="lulu-completion__button" key={option.id} disabled={busy === request.id} onClick={() => void resolve(request, option.id)}>{option.label}</button>)}</div>}</article>)}{requests.length === 0 && <div className="lulu-completion__empty"><CheckCircle2 size={20} /><p>No executive decision request needs a response.</p></div>}</div></PanelCard>;
}

export function WorkforceControlCenterCompletion() {
  const { selectedWorkspace } = useLuluApp(); const workspaceId = selectedWorkspace?.id ?? null; const location = useLocation(); const navigate = useNavigate();
  const query = useMemo(() => new URLSearchParams(location.search), [location.search]); const requestedPanel = query.get("control") as Panel | null; const panel: Panel = requestedPanel && ["overview", "workflow", "goals", "playbooks", "autonomy", "decisions", "incidents"].includes(requestedPanel) ? requestedPanel : "overview"; const workflowId = query.get("workflowId");
  const setPanel = (next: Panel) => { const nextQuery = new URLSearchParams(location.search); nextQuery.set("control", next); navigate({ pathname: location.pathname, search: `?${nextQuery.toString()}` }, { replace: true }); };
  if (!workspaceId) return null;
  return <section className="lulu-completion" aria-label="Workforce operations completion"><header className="lulu-completion__header"><div><span className="lulu-completion__eyebrow">Operational cockpit</span><h2>Workforce Control Center</h2><p>Trace goals, workflows, agents, tools, approvals, verification and outcomes from the same workspace-scoped records.</p></div><button type="button" className="lulu-completion__button" onClick={() => window.location.reload()}><RefreshCw size={14} />Refresh surface</button></header><nav className="lulu-completion__tabs" aria-label="Workforce control center sections">{(["overview", "workflow", "goals", "playbooks", "autonomy", "decisions", "incidents"] as Panel[]).map((item) => <button type="button" key={item} className={panel === item ? "is-active" : ""} onClick={() => setPanel(item)}>{humanize(item)}</button>)}</nav>{panel === "overview" && <div className="lulu-completion__overview-grid"><PanelCard title="Operational answers" eyebrow="Business view"><div className="lulu-completion__answer-grid"><div><strong>What is Lulu doing?</strong><span>See the verified active work projection above.</span></div><div><strong>Why?</strong><span>Trace each task to its workflow, mission and goal.</span></div><div><strong>What needs attention?</strong><span>Only approvals, incidents, decisions and blocked work belong in the queue.</span></div><div><strong>What was verified?</strong><span>Inspect tool verification and execution receipts in the workflow view.</span></div></div></PanelCard><PanelCard title="Outcome separation" eyebrow="Never collapse these states"><div className="lulu-completion__outcome-layers"><div><CheckCircle2 size={16} /><strong>Task execution</strong><span>Did the task reach a terminal state?</span></div><div><ShieldCheck size={16} /><strong>Action verification</strong><span>Did the authoritative state match?</span></div><div><Target size={16} /><strong>Business outcome</strong><span>Did the KPI move as measured?</span></div></div></PanelCard></div>}{panel === "workflow" && <WorkflowInspector workspaceId={workspaceId} initialWorkflowId={workflowId} />}{panel === "goals" && <GoalsPanel workspaceId={workspaceId} />}{panel === "playbooks" && <PlaybooksPanel workspaceId={workspaceId} />}{panel === "autonomy" && <AutonomyPanel workspaceId={workspaceId} />}{panel === "decisions" && <DecisionsPanel workspaceId={workspaceId} />}{panel === "incidents" && <AutonomyPanel workspaceId={workspaceId} />}</section>;
}
