import { ArrowRight,CheckCircle2,FileText,LoaderCircle,Sparkles,Trash2,UploadCloud } from 'lucide-react';
import { useEffect,useState } from 'react';
import { getFriendlyErrorMessage } from '../api/client';
import { useLuluApp } from '../api/LuluAppContext';
import { onboardingApi,type OnboardingDocument } from '../api/onboarding';
import { navigateApp,routes } from '../routing';
import { OnboardingHeader } from './OnboardingHeader';

export function KnowledgeActivationGate(){
  const{selectedWorkspace,refresh}=useLuluApp();const workspaceId=selectedWorkspace?.id??null;
  const[text,setText]=useState('');const[documents,setDocuments]=useState<OnboardingDocument[]>([]);
  const[loading,setLoading]=useState(true);const[uploading,setUploading]=useState(false);const[processing,setProcessing]=useState(false);const[error,setError]=useState('');
  useEffect(()=>{if(!workspaceId){setLoading(false);return;}void onboardingApi.documents(workspaceId).then(result=>setDocuments(result.data.items)).catch(cause=>setError(getFriendlyErrorMessage(cause,'Documents could not be loaded.'))).finally(()=>setLoading(false));},[workspaceId]);
  async function upload(file:File|undefined){if(!file||!workspaceId||uploading||documents.length>=10)return;setUploading(true);setError('');try{const response=await onboardingApi.uploadDocument(workspaceId,file);setDocuments(current=>[...current,response.data]);}catch(cause){setError(getFriendlyErrorMessage(cause,'The document could not be uploaded.'));}finally{setUploading(false);}}
  async function remove(document:OnboardingDocument){if(!workspaceId)return;setError('');try{await onboardingApi.deleteDocument(workspaceId,document.id);setDocuments(current=>current.filter(item=>item.id!==document.id));}catch(cause){setError(getFriendlyErrorMessage(cause,'The document could not be removed.'));}}
  async function activate(){if(!workspaceId||processing||(!text.trim()&&documents.length===0))return;setProcessing(true);setError('');try{await onboardingApi.activateKnowledge(workspaceId,{text:text.trim(),documentIds:documents.map(item=>item.id)});await refresh();navigateApp(routes.app.dashboard,{replace:true});}catch(cause){setError(getFriendlyErrorMessage(cause,'Lulu could not finish processing the Knowledge Base.'));setProcessing(false);}}
  return <div className="mx-auto max-w-5xl space-y-6 pb-12"><OnboardingHeader step={4} showBrandName={false}/>
    <header className="rounded-3xl border border-violet-500/20 bg-[radial-gradient(circle_at_top_right,rgba(124,58,237,.14),transparent_42%),var(--card)] p-6 shadow-sm sm:p-9"><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-700">Activation gate · final step</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Give Lulu the truth. Lulu builds the operating intelligence.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">Add products, services, documents or any useful company information. AI classifies everything, creates detected catalog items and queues missing premium product images automatically.</p></header>
    {error?<div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>:null}
    <section className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><Sparkles size={20}/><div><h2 className="font-semibold">Company knowledge</h2><p className="text-sm text-muted-foreground">Paste everything in any structure or language.</p></div></div><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Products, services, positioning, processes, FAQs, policies, brand story, customer information…" className="mt-5 min-h-72 w-full resize-y rounded-xl border border-border bg-background p-4 text-sm leading-6 outline-none focus:ring-2 focus:ring-primary" maxLength={50000}/><p className="mt-2 text-right text-xs text-muted-foreground">{text.length.toLocaleString()} / 50,000</p></div>
      <div className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><FileText size={20}/><div><h2 className="font-semibold">Business documents</h2><p className="text-sm text-muted-foreground">PDF, text, CSV, Office files or images · max. 5 MB · up to 10 files</p></div></div><label className={`mt-5 flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-background/50 px-4 py-8 text-center ${documents.length>=10?'cursor-not-allowed opacity-50':'cursor-pointer hover:bg-secondary'}`}><input type="file" className="sr-only" disabled={uploading||documents.length>=10} onChange={event=>{void upload(event.target.files?.[0]);event.currentTarget.value='';}}/><UploadCloud size={24}/><span className="mt-3 text-sm font-semibold">{uploading?'Uploading…':documents.length>=10?'Document limit reached':'Choose a document'}</span></label><div className="mt-4 space-y-2">{loading?<p className="text-sm text-muted-foreground">Loading documents…</p>:documents.length===0?<p className="rounded-xl bg-secondary p-4 text-sm text-muted-foreground">No documents added yet.</p>:documents.map(document=><div key={document.id} className="flex items-center justify-between gap-3 rounded-xl border border-border p-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{document.fileName}</p><p className="text-xs text-muted-foreground">{Math.ceil(document.sizeBytes/1024).toLocaleString()} KB</p></div><button type="button" onClick={()=>void remove(document)} className="rounded-lg p-2 hover:bg-secondary" aria-label={`Remove ${document.fileName}`}><Trash2 size={15}/></button></div>)}</div></div></section>
    <section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5 sm:flex sm:items-center sm:justify-between sm:gap-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-600" size={20}/><div><h2 className="font-semibold">One intelligent activation</h2><p className="mt-1 text-sm text-muted-foreground">The workspace unlocks only after classification and durable storage succeed. Normal agents start when AI and ad-spend wallets are funded.</p></div></div><button type="button" onClick={()=>void activate()} disabled={processing||(!text.trim()&&documents.length===0)} className="mt-5 inline-flex w-full shrink-0 items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-40 sm:mt-0 sm:w-auto">{processing?<LoaderCircle className="animate-spin" size={17}/>:<ArrowRight size={17}/>} {processing?'AI is structuring your company…':'Activate Lulu'}</button></section>
  </div>;
}
