import { useEffect, useState } from "react";
import type { TemplateCopy, TemplateLocale } from "./ManagedStorefrontApp";

const PAGE = { landing: "0", catalog: "1", offerings: "2", contact: "3" } as const;
type Page = (typeof PAGE)[keyof typeof PAGE];
type Props = { copy: TemplateCopy; locale: TemplateLocale; setLocale: (locale: TemplateLocale) => void; hasServices: boolean; hasProducts: boolean };

const imageRoot = "/templates/lulu-industrial";
const productImages = ["large-bolts.jpg", "solar-fasteners.jpg", "custom-drawing.jpg", "hero-fasteners.jpg"];
const serviceImages = ["custom-drawing.jpg", "solar-fasteners.jpg", "large-bolts.jpg", "hero-fasteners.jpg"];

function Placeholder({ src, alt, className = "" }: { src: string; alt: string; className?: string }) {
  return <div className={`relative overflow-hidden bg-[#eef0f3] ${className}`}><img src={`${imageRoot}/${src}`} alt={alt} className="h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-tr from-[#102b50]/35 via-transparent to-[#f26904]/20" /></div>;
}

function Field({ label, type = "text" }: { label: string; type?: "text" | "email" | "file" }) {
  return <label className="text-xs font-semibold uppercase tracking-[.12em] text-[#5e646c]">{label}<input disabled type={type} className="mt-2 h-11 w-full border border-[#dbdee2] bg-white px-3 text-sm normal-case tracking-normal text-[#5e646c] outline-none" placeholder={label} /></label>;
}

function ContactSection({ copy }: { copy: TemplateCopy }) {
  return <section id="contact" className="scroll-mt-5 px-5 py-12 sm:px-10 sm:py-16"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f26904]">{copy.messageLabel}</p><h4 className="mt-3 text-3xl font-bold text-[#1a3a68]">{copy.formTitle}</h4><p className="mt-3 text-sm leading-7 text-[#5e646c]">{copy.formBody}</p></div><div className="grid gap-4 border border-[#dbdee2] bg-white p-5 sm:grid-cols-2"><Field label={copy.name} /><Field label={copy.email} type="email" /><Field label={copy.website} /><Field label={copy.whatsapp} /><label className="text-xs font-semibold uppercase tracking-[.12em] text-[#5e646c]">{copy.file}<input disabled type="file" className="mt-2 h-11 w-full border border-[#dbdee2] bg-white px-3 text-sm normal-case tracking-normal text-[#5e646c] outline-none" /><span className="mt-1 block text-[10px] font-normal normal-case tracking-normal text-[#5e646c]">{copy.fileHint}</span></label><label className="text-xs font-semibold uppercase tracking-[.12em] text-[#5e646c] sm:col-span-2">{copy.message}<textarea disabled rows={4} className="mt-2 w-full resize-none border border-[#dbdee2] bg-white p-3 text-sm normal-case tracking-normal text-[#5e646c] outline-none" placeholder={copy.message} /></label><a href="#contact" className="inline-flex h-11 w-fit items-center bg-[#f26904] px-5 text-sm font-bold text-white hover:bg-[#d85e04]">{copy.send}</a></div></div></section>;
}

function ProductsSection({ copy }: { copy: TemplateCopy }) {
  return <section id="product-catalog" className="scroll-mt-5 px-5 py-12 sm:px-10 sm:py-16"><div className="mx-auto max-w-[1280px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f26904]">{copy.products}</p><h4 className="mt-3 text-3xl font-bold leading-tight text-[#1a3a68] sm:text-4xl">{copy.productsTitle}</h4><p className="mt-3 max-w-2xl text-sm leading-7 text-[#5e646c]">{copy.productsBody}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{copy.productNames.map((name, index) => <article key={name} className="overflow-hidden border border-[#dbdee2] bg-white"><Placeholder src={productImages[index]} alt={`${copy.productImage}: ${name}`} className="h-44" /><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#5e646c]">{copy.productLabel}</p><h5 className="mt-2 font-bold text-[#1a3a68]">{name}</h5><p className="mt-3 text-sm text-[#5e646c]">{copy.priceOnRequest}</p><a href="#contact" className="mt-4 inline-flex text-xs font-bold uppercase tracking-[.1em] text-[#f26904]">{copy.more}</a></div></article>)}</div></div></section>;
}

function ServicesSection({ copy }: { copy: TemplateCopy }) {
  return <section id="service-list" className="scroll-mt-5 bg-[#eef0f3] px-5 py-12 sm:px-10 sm:py-16"><div className="mx-auto max-w-[1280px]"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f26904]">{copy.services}</p><h4 className="mt-3 text-3xl font-bold leading-tight text-[#1a3a68] sm:text-4xl">{copy.servicesTitle}</h4><p className="mt-3 max-w-2xl text-sm leading-7 text-[#5e646c]">{copy.servicesBody}</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{copy.serviceCards.map((title, index) => <article key={title} className="border border-[#dbdee2] bg-white p-5"><Placeholder src={serviceImages[index]} alt={copy.serviceImage} className="h-36" /><p className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-[#5e646c]">{copy.serviceArea}</p><h5 className="mt-2 text-lg font-bold text-[#1a3a68]">{title}</h5><a href="#contact" className="mt-4 inline-flex text-xs font-bold uppercase tracking-[.1em] text-[#f26904]">{copy.view}</a></article>)}</div></div></section>;
}

function IndustrialHeader({ copy, locale, setLocale, page, setPage, hasServices, productsEnabled, setProductsEnabled }: { copy: TemplateCopy; locale: TemplateLocale; setLocale: (locale: TemplateLocale) => void; page: Page; setPage: (page: Page) => void; hasServices: boolean; productsEnabled: boolean; setProductsEnabled: (enabled: boolean) => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const go = (next: Page) => { setPage(next); setMenuOpen(false); window.location.hash = next; };
  const items: Array<[string, Page]> = [[copy.home, PAGE.landing], [copy.solutions, PAGE.landing], ...(productsEnabled ? [[copy.products, PAGE.catalog] as [string, Page]] : []), ...(hasServices ? [[copy.services, PAGE.offerings] as [string, Page]] : []), [copy.about, PAGE.landing], [copy.contact, PAGE.contact]];
  return <>
    <div className="bg-[#181f27] px-5 py-2 text-[10px] font-semibold uppercase tracking-[.14em] text-white/75 sm:px-10"><div className="mx-auto flex max-w-[1280px] flex-wrap items-center justify-between gap-2"><span>{copy.templateKicker}</span><span>{copy.templateMode}</span></div></div>
    <header className="border-b border-[#dbdee2] bg-white px-5 py-5 sm:px-10"><div className="mx-auto flex max-w-[1280px] flex-wrap items-center justify-between gap-4"><a href="#start" onClick={(event) => { event.preventDefault(); go(PAGE.landing); }} className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center bg-[#1a3a68] text-lg font-bold text-white">L</span><span className="min-w-0"><span className="block truncate text-sm font-bold tracking-[.08em] text-[#1a3a68]">{copy.brand}</span><span className="block text-[10px] font-semibold uppercase tracking-[.2em] text-[#5e646c]">{copy.templateSubline}</span></span></a><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="inline-flex h-9 items-center border border-[#dbdee2] px-3 text-xs font-bold uppercase tracking-[.1em] text-[#1a3a68] md:hidden">{menuOpen ? copy.close : copy.menu}</button><nav className={`${menuOpen ? "flex" : "hidden"} w-full flex-col gap-3 border-t border-[#dbdee2] pt-4 text-xs font-semibold uppercase tracking-[.08em] text-[#5e646c] md:flex md:w-auto md:flex-row md:border-0 md:pt-0`}>{items.map(([label, target]) => <a key={label} href={`#${target}`} onClick={(event) => { event.preventDefault(); go(target); }} className={`${target === page ? "text-[#f26904]" : "hover:text-[#f26904]"}`}>{label}</a>)}</nav><div className="ml-auto flex items-center gap-2"><label className="sr-only" htmlFor="lulu-industrial-language">{copy.language}</label><select id="lulu-industrial-language" value={locale} onChange={(event) => setLocale(event.target.value as TemplateLocale)} className="h-9 border border-[#dbdee2] bg-white px-2 text-xs font-semibold text-[#1a3a68] outline-none"><option value="de">{copy.languageDe}</option><option value="en">{copy.languageEn}</option><option value="zh">{copy.languageZh}</option></select><button type="button" onClick={() => setProductsEnabled(!productsEnabled)} className="hidden h-9 border border-[#1a3a68] px-3 text-[10px] font-bold uppercase tracking-[.08em] text-[#1a3a68] sm:inline-flex sm:items-center">{productsEnabled ? copy.productsOff : copy.productsOn}</button><a href="#contact" onClick={(event) => { event.preventDefault(); go(PAGE.contact); }} className="hidden border border-[#1a3a68] px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-[#1a3a68] hover:bg-[#1a3a68] hover:text-white sm:inline-flex">{copy.contact}</a></div></div></header>
  </>;
}

export function LuluIndustrialTemplate({ copy, locale, setLocale, hasServices, hasProducts }: Props) {
  const initialPage = (): Page => { const value = window.location.hash.replace(/^#/, ""); return value === PAGE.catalog ? PAGE.catalog : value === PAGE.offerings ? PAGE.offerings : value === PAGE.contact ? PAGE.contact : PAGE.landing; };
  const [page, setPage] = useState<Page>(initialPage);
  const [productsEnabled, setProductsEnabled] = useState(hasProducts);
  useEffect(() => { const onHash = () => { const value = window.location.hash.replace(/^#/, ""); if (value === PAGE.catalog) setPage(PAGE.catalog); else if (value === PAGE.offerings) setPage(PAGE.offerings); else if (value === PAGE.contact) setPage(PAGE.contact); else if (value === PAGE.landing) setPage(PAGE.landing); }; window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash); }, []);
  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, [page]);
  const solutionCards = [{ number: "01", title: copy.company, body: copy.companyBody }, { number: "02", title: copy.offer, body: copy.offerBody }, { number: "03", title: copy.trustTitle, body: copy.trustBody }, { number: "04", title: copy.contactTitle, body: copy.contactBody }];
  const go = (next: Page) => { setPage(next); window.location.hash = next; };
  return <div className="mt-6 overflow-hidden border border-[#dbdee2] bg-[#fdfdfe] text-[#121921] shadow-sm"><IndustrialHeader copy={copy} locale={locale} setLocale={setLocale} page={page} setPage={setPage} hasServices={hasServices} productsEnabled={productsEnabled} setProductsEnabled={setProductsEnabled} />
    {page === PAGE.landing ? <>
      <section id="start" className="bg-[#1a3a68] px-5 py-10 text-white sm:px-10 sm:py-16"><div className="mx-auto grid max-w-[1280px] items-stretch gap-8 lg:grid-cols-[1.04fr_.96fr]"><div className="flex flex-col justify-center"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#f7a466]">{copy.heroEyebrow}</p><h3 className="mt-4 max-w-3xl text-4xl font-bold leading-[.95] tracking-[-.04em] sm:text-6xl">{copy.heroTitle}</h3><p className="mt-6 max-w-xl text-base leading-7 text-white/75 sm:text-lg">{copy.starterCopy}</p><div className="mt-8 flex flex-wrap gap-3"><a href="#contact" onClick={(event) => { event.preventDefault(); go(PAGE.contact); }} className="inline-flex h-11 items-center bg-[#f26904] px-5 text-sm font-bold text-white hover:bg-[#d85e04]">{copy.speak}</a><a href="#service-list" onClick={(event) => { event.preventDefault(); go(PAGE.offerings); }} className="inline-flex h-11 items-center border border-white/40 px-5 text-sm font-bold text-white hover:bg-white/10">{copy.viewServices}</a></div></div><Placeholder src="hero-fasteners.jpg" alt={copy.heroImage} className="min-h-64 border-8 border-white/10 sm:min-h-80" /></div></section>
      <section className="border-b border-[#dbdee2] bg-[#eef0f3] px-5 py-5 sm:px-10"><div className="mx-auto grid max-w-[1280px] gap-4 text-center text-xs font-bold uppercase tracking-[.12em] text-[#1a3a68] sm:grid-cols-3">{copy.trust.slice(0, 3).map((item) => <span key={item} className="border-l-2 border-[#f26904] px-3">{item}</span>)}</div></section>
      <section id="solutions" className="scroll-mt-5 px-5 py-12 sm:px-10 sm:py-16"><div className="mx-auto max-w-[1280px]"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f26904]">{copy.solutions}</p><h4 className="mt-3 text-3xl font-bold leading-tight tracking-[-.03em] text-[#121921] sm:text-5xl">{copy.solutionsTitle}</h4><p className="mt-4 text-sm leading-7 text-[#5e646c]">{copy.solutionsDescription}</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{solutionCards.map((card) => <article key={card.number} className="flex min-h-52 flex-col border border-[#dbdee2] bg-white p-5"><span className="text-xs font-bold tracking-[.12em] text-[#f26904]">{card.number}</span><h5 className="mt-8 text-xl font-bold text-[#1a3a68]">{card.title}</h5><p className="mt-3 flex-1 text-sm leading-6 text-[#5e646c]">{card.body}</p><a href={card.number === "04" ? "#contact" : card.number === "02" ? "#product-catalog" : "#about"} className="mt-5 text-xs font-bold uppercase tracking-[.1em] text-[#f26904]">{copy.more}</a></article>)}</div></div></section>
      {hasServices ? <ServicesSection copy={copy} /> : null}{productsEnabled ? <ProductsSection copy={copy} /> : null}
      <section id="about" className="scroll-mt-5 bg-[#181f27] px-5 py-12 text-white sm:px-10 sm:py-16"><div className="mx-auto grid max-w-[1280px] items-center gap-9 lg:grid-cols-[.8fr_1.2fr]"><Placeholder src="custom-drawing.jpg" alt={copy.companyImage} className="min-h-64 border border-white/15" /><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#f7a466]">{copy.strengthsLabel}</p><h4 className="mt-3 text-3xl font-bold leading-tight sm:text-4xl">{copy.strengthsTitle}</h4><p className="mt-4 max-w-2xl text-sm leading-7 text-white/70">{copy.strengthsBody}</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{copy.strengths.map((item) => <div key={item} className="border border-white/15 bg-white/5 p-4 text-sm font-semibold">{item}</div>)}</div></div></div></section><ContactSection copy={copy} />
    </> : page === PAGE.catalog ? <><ProductsSection copy={copy} /><ContactSection copy={copy} /></> : page === PAGE.offerings ? <><ServicesSection copy={copy} /><ContactSection copy={copy} /></> : <ContactSection copy={copy} />}
    <footer className="flex flex-col gap-3 border-t border-[#dbdee2] bg-[#181f27] px-5 py-7 text-xs text-white/60 sm:flex-row sm:items-center sm:justify-between sm:px-10"><a href="#start" onClick={(event) => { event.preventDefault(); go(PAGE.landing); }} className="font-bold tracking-[.1em] text-white">{copy.footerBrand}</a><span>{copy.legal}</span><span>{copy.footerBrand}</span></footer>
  </div>;
}
