import { useEffect, useMemo, useState } from 'react';
import { Archive, ChevronRight, Package, Plus, RefreshCw, Save, Search, X } from 'lucide-react';
import { useLuluApp } from '../../api/LuluAppContext';
import { productsApi, type Product, type ProductDetail } from '../../api/products';
import { getFriendlyErrorMessage } from '../../api/client';

const emptyForm = { name: '', sku: '', productType: 'PHYSICAL_PRODUCT', status: 'DRAFT', shortDescription: '', longDescription: '', defaultCurrency: 'CNY', defaultPrice: '', pricingType: 'QUOTE_REQUIRED', moqQuantity: '', moqUnit: '', leadTimeMinDays: '', leadTimeMaxDays: '' };
type Form = typeof emptyForm;
export default function ProductsPage() {
  const { selectedWorkspace, permissions } = useLuluApp();
  const [items, setItems] = useState<Product[]>([]); const [selected, setSelected] = useState<ProductDetail | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [editing, setEditing] = useState(false); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const canWrite = permissions.canEdit;
  const load = async () => { if (!selectedWorkspace) return; setLoading(true); setError(''); try { const result = await productsApi.list(selectedWorkspace.id, new URLSearchParams({ ...(search ? { search } : {}) }).toString()); setItems(result.data.items); if (selected) { const next = await productsApi.get(selectedWorkspace.id, selected.id); setSelected(next.data); } } catch (e) { setError(getFriendlyErrorMessage(e, 'Produkte konnten nicht geladen werden.')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [selectedWorkspace?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  const open = async (product: Product) => { if (!selectedWorkspace) return; try { const result = await productsApi.get(selectedWorkspace.id, product.id); setSelected(result.data); setForm({ ...emptyForm, ...Object.fromEntries(Object.entries(emptyForm).map(([key]) => [key, String((result.data as any)[key] ?? '')])) } as Form); setEditing(false); } catch (e) { setError(getFriendlyErrorMessage(e, 'Produkt konnte nicht geladen werden.')); } };
  const save = async () => { if (!selectedWorkspace || !form.name.trim()) return; setSaving(true); setError(''); const body: Record<string, unknown> = { ...form, defaultPrice: form.defaultPrice || null, moqQuantity: form.moqQuantity || null, leadTimeMinDays: form.leadTimeMinDays || null, leadTimeMaxDays: form.leadTimeMaxDays || null, sku: form.sku || null, shortDescription: form.shortDescription || null, longDescription: form.longDescription || null }; try { if (selected) { const result = await productsApi.update(selectedWorkspace.id, selected.id, body); setSelected(result.data); } else { const result = await productsApi.create(selectedWorkspace.id, body); setSelected(result.data); } setEditing(false); setForm(emptyForm); await load(); } catch (e) { setError(getFriendlyErrorMessage(e, 'Produkt konnte nicht gespeichert werden.')); } finally { setSaving(false); } };
  const archive = async () => { if (!selectedWorkspace || !selected || !window.confirm('Produkt archivieren?')) return; try { await productsApi.archive(selectedWorkspace.id, selected.id); setSelected(null); await load(); } catch (e) { setError(getFriendlyErrorMessage(e, 'Produkt konnte nicht archiviert werden.')); } };
  const stats = useMemo(() => ({ total: items.length, active: items.filter((p) => p.status === 'ACTIVE').length, ready: items.filter((p) => p.completeness?.readyForPublishing).length }), [items]);
  if (!selectedWorkspace) return <main className="page-frame p-8"><h1 className="text-2xl font-semibold">Product Master</h1><p className="mt-2 text-[var(--muted-foreground)]">Choose a workspace to manage products.</p></main>;
  return <main className="page-frame min-h-screen bg-[var(--background)] p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Lulu Product Master</p><h1 className="text-3xl font-semibold tracking-tight">Products</h1><p className="mt-1 text-sm text-[var(--muted-foreground)]">One canonical source for product data, localization and publishing.</p></div><button disabled={!canWrite} onClick={() => { setSelected(null); setForm(emptyForm); setEditing(true); }} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--foreground)] px-4 py-2.5 text-sm font-medium text-[var(--background)] disabled:cursor-not-allowed disabled:opacity-40"><Plus size={16}/> New product</button></header>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Total products" value={stats.total}/><Stat label="Active" value={stats.active}/><Stat label="Ready to publish" value={stats.ready}/></div>
    {error ? <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div> : null}
    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.9fr)]"><div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] shadow-sm"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-[var(--muted-foreground)]"/><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void load()} placeholder="Search name or SKU" className="w-full rounded-xl border border-[var(--border)] bg-transparent py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-[var(--ring)]"/></label><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-3 py-2 text-sm"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/> Refresh</button></div><div className="divide-y divide-[var(--border)]">{!loading && items.length === 0 ? <div className="p-10 text-center text-sm text-[var(--muted-foreground)]"><Package className="mx-auto mb-3 opacity-50"/><p>No products yet.</p><p className="mt-1">Create your first canonical product to begin.</p></div> : items.map((product) => <button key={product.id} onClick={() => void open(product)} className={`flex w-full items-center justify-between gap-4 p-4 text-left transition hover:bg-[var(--secondary)] ${selected?.id === product.id ? 'bg-[var(--secondary)]' : ''}`}><div className="min-w-0"><div className="truncate font-medium">{product.name}</div><div className="mt-1 flex flex-wrap gap-2 text-xs text-[var(--muted-foreground)]"><span>{product.sku || 'No SKU'}</span><span>•</span><span>{product.productType.replaceAll('_', ' ')}</span></div></div><div className="flex items-center gap-3"><span className="rounded-full bg-[var(--secondary)] px-2.5 py-1 text-xs">{product.status}</span><ChevronRight size={16} className="text-[var(--muted-foreground)]"/></div></button>)}</div></div>
      <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] shadow-sm">{editing ? <FormPanel form={form} setForm={setForm} saving={saving} onSave={() => void save()} onCancel={() => { setEditing(false); setForm(emptyForm); }} /> : selected ? <DetailPanel product={selected} canWrite={canWrite} onEdit={() => { setEditing(true); setForm({ ...emptyForm, ...Object.fromEntries(Object.entries(emptyForm).map(([key]) => [key, String((selected as any)[key] ?? '')])) } as Form); }} onArchive={() => void archive()} /> : <div className="grid min-h-[420px] place-items-center p-8 text-center text-sm text-[var(--muted-foreground)]"><div><Package size={34} className="mx-auto mb-3 opacity-40"/><p>Select a product to inspect its master data.</p></div></div>}</div></section></div></main>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-4"><div className="text-xs uppercase tracking-[0.16em] text-[var(--muted-foreground)]">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>; }
function FormPanel({ form, setForm, saving, onSave, onCancel }: { form: Form; setForm: (f: Form) => void; saving: boolean; onSave: () => void; onCancel: () => void }) { const update = (key: keyof Form, value: string) => setForm({ ...form, [key]: value }); return <div className="p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">Product master data</h2><button onClick={onCancel} aria-label="Close"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2">{([['name','Name'],['sku','SKU'],['shortDescription','Short description'],['defaultCurrency','Currency'],['defaultPrice','Default price'],['moqQuantity','MOQ quantity'],['moqUnit','MOQ unit'],['leadTimeMinDays','Min. lead time (days)'],['leadTimeMaxDays','Max. lead time (days)']] as [keyof Form,string][]).map(([key,label]) => <label key={key} className={key === 'shortDescription' ? 'sm:col-span-2' : ''}><span className="mb-1 block text-xs font-medium text-[var(--muted-foreground)]">{label}</span><input value={form[key]} onChange={(e) => update(key,e.target.value)} className="w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[var(--ring)]"/></label>)}<label><span className="mb-1 block text-xs font-medium text-[var(--muted-foreground)]">Product type</span><select value={form.productType} onChange={(e) => update('productType',e.target.value)} className="w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2.5 text-sm"><option value="PHYSICAL_PRODUCT">Physical product</option><option value="CUSTOM_MANUFACTURING">Custom manufacturing</option><option value="OEM">OEM</option><option value="ODM">ODM</option><option value="SERVICE">Service</option></select></label><label><span className="mb-1 block text-xs font-medium text-[var(--muted-foreground)]">Status</span><select value={form.status} onChange={(e) => update('status',e.target.value)} className="w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2.5 text-sm"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="sm:col-span-2"><span className="mb-1 block text-xs font-medium text-[var(--muted-foreground)]">Long description</span><textarea value={form.longDescription} onChange={(e) => update('longDescription',e.target.value)} rows={5} className="w-full rounded-xl border border-[var(--border)] bg-transparent px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-[var(--ring)]"/></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={onCancel} className="rounded-xl border border-[var(--border)] px-4 py-2 text-sm">Cancel</button><button disabled={saving || !form.name.trim()} onClick={onSave} className="inline-flex items-center gap-2 rounded-xl bg-[var(--foreground)] px-4 py-2 text-sm text-[var(--background)] disabled:opacity-40"><Save size={15}/>{saving ? 'Saving…' : 'Save product'}</button></div></div>; }
function DetailPanel({ product, canWrite, onEdit, onArchive }: { product: ProductDetail; canWrite: boolean; onEdit: () => void; onArchive: () => void }) { const c = product.completeness; return <div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-[var(--muted-foreground)]">{product.status}</p><h2 className="mt-1 text-2xl font-semibold">{product.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{product.sku || 'No SKU assigned'}</p></div><div className="flex gap-2"><button disabled={!canWrite} onClick={onEdit} className="rounded-xl border border-[var(--border)] px-3 py-2 text-sm disabled:opacity-40">Edit</button><button disabled={!canWrite} onClick={onArchive} aria-label="Archive product" className="rounded-xl border border-rose-200 p-2 text-rose-700 disabled:opacity-40"><Archive size={16}/></button></div></div><div className="mt-6 rounded-xl bg-[var(--secondary)] p-4"><div className="flex items-center justify-between text-sm"><span>Completeness</span><strong>{c?.score ?? 0}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--background)]"><div className="h-full rounded-full bg-violet-500" style={{ width: `${c?.score ?? 0}%` }}/></div>{c?.missing?.length ? <p className="mt-2 text-xs text-[var(--muted-foreground)]">Missing: {c.missing.join(', ')}</p> : <p className="mt-2 text-xs text-emerald-700">Ready for publishing</p>}</div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><Info label="Type" value={product.productType.replaceAll('_', ' ')}/><Info label="Pricing" value={`${product.defaultCurrency || ''} ${product.defaultPrice || 'Quote required'}`}/><Info label="MOQ" value={product.moqQuantity ? `${product.moqQuantity} ${product.moqUnit || ''}` : 'Not set'}/><Info label="Lead time" value={product.leadTimeMinDays != null ? `${product.leadTimeMinDays}–${product.leadTimeMaxDays ?? product.leadTimeMinDays} days` : 'Not set'}/><Info label="Variants" value={String(product.variants?.length ?? 0)}/><Info label="Translations" value={String(product.translations?.length ?? 0)}/><Info label="Markets" value={String(product.markets?.length ?? 0)}/><Info label="Media" value={String(product.media?.length ?? 0)}/></dl><p className="mt-6 text-sm leading-6 text-[var(--muted-foreground)]">{product.longDescription || product.shortDescription || 'No description yet.'}</p></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-[var(--muted-foreground)]">{label}</dt><dd className="mt-1 font-medium capitalize">{value}</dd></div>; }
