import json
from pathlib import Path

root = Path('/home/ubuntu/lulu-growth-frontend/src/i18n/runtime-overrides')
translations = {
    'de': {'WordPress':'WordPress','Website generation':'Website-Generierung','Choose the connected website and domain, then generate or update the website.':'Wähle die verbundene Website und Domain aus und generiere oder aktualisiere die Website.','Generating…':'Wird generiert…','Generation in progress…':'Generierung läuft…','Generate website':'Website generieren','Website':'Website','Select website':'Website auswählen','Domain':'Domain','Select domain':'Domain auswählen','No domain available':'Keine Domain verfügbar','Verified':'Verifiziert','Pending verification':'Verifizierung ausstehend'},
    'fr': {'WordPress':'WordPress','Website generation':'Génération du site web','Choose the connected website and domain, then generate or update the website.':'Choisissez le site et le domaine connectés, puis générez ou mettez à jour le site.','Generating…':'Génération…','Generation in progress…':'Génération en cours…','Generate website':'Générer le site web','Website':'Site web','Select website':'Sélectionner un site','Domain':'Domaine','Select domain':'Sélectionner un domaine','No domain available':'Aucun domaine disponible','Verified':'Vérifié','Pending verification':'Vérification en attente'},
    'nl': {'WordPress':'WordPress','Website generation':'Websitegeneratie','Choose the connected website and domain, then generate or update the website.':'Kies de verbonden website en het domein en genereer of werk de website bij.','Generating…':'Wordt gegenereerd…','Generation in progress…':'Generatie bezig…','Generate website':'Website genereren','Website':'Website','Select website':'Website selecteren','Domain':'Domein','Select domain':'Domein selecteren','No domain available':'Geen domein beschikbaar','Verified':'Geverifieerd','Pending verification':'Verificatie in behandeling'},
    'pl': {'WordPress':'WordPress','Website generation':'Generowanie strony','Choose the connected website and domain, then generate or update the website.':'Wybierz połączoną stronę i domenę, a następnie wygeneruj lub zaktualizuj stronę.','Generating…':'Generowanie…','Generation in progress…':'Generowanie w toku…','Generate website':'Generuj stronę','Website':'Strona','Select website':'Wybierz stronę','Domain':'Domena','Select domain':'Wybierz domenę','No domain available':'Brak dostępnej domeny','Verified':'Zweryfikowana','Pending verification':'Weryfikacja oczekuje'},
    'nb': {'WordPress':'WordPress','Website generation':'Generering av nettsted','Choose the connected website and domain, then generate or update the website.':'Velg det tilkoblede nettstedet og domenet, og generer eller oppdater nettstedet.','Generating…':'Genererer…','Generation in progress…':'Generering pågår…','Generate website':'Generer nettsted','Website':'Nettsted','Select website':'Velg nettsted','Domain':'Domene','Select domain':'Velg domene','No domain available':'Ingen domene tilgjengelig','Verified':'Verifisert','Pending verification':'Venter på verifisering'},
    'sv': {'WordPress':'WordPress','Website generation':'Webbplatsgenerering','Choose the connected website and domain, then generate or update the website.':'Välj den anslutna webbplatsen och domänen och generera eller uppdatera webbplatsen.','Generating…':'Genererar…','Generation in progress…':'Generering pågår…','Generate website':'Generera webbplats','Website':'Webbplats','Select website':'Välj webbplats','Domain':'Domän','Select domain':'Välj domän','No domain available':'Ingen domän tillgänglig','Verified':'Verifierad','Pending verification':'Verifiering väntar'},
    'fi': {'WordPress':'WordPress','Website generation':'Verkkosivuston luonti','Choose the connected website and domain, then generate or update the website.':'Valitse yhdistetty verkkosivusto ja verkkotunnus ja luo tai päivitä verkkosivusto.','Generating…':'Luodaan…','Generation in progress…':'Luonti käynnissä…','Generate website':'Luo verkkosivusto','Website':'Verkkosivusto','Select website':'Valitse verkkosivusto','Domain':'Verkkotunnus','Select domain':'Valitse verkkotunnus','No domain available':'Verkkotunnusta ei ole saatavilla','Verified':'Vahvistettu','Pending verification':'Vahvistus odottaa'},
    'da': {'WordPress':'WordPress','Website generation':'Generering af websted','Choose the connected website and domain, then generate or update the website.':'Vælg det tilsluttede websted og domænet, og generer eller opdater webstedet.','Generating…':'Genererer…','Generation in progress…':'Generering i gang…','Generate website':'Generer websted','Website':'Websted','Select website':'Vælg websted','Domain':'Domæne','Select domain':'Vælg domæne','No domain available':'Intet domæne tilgængeligt','Verified':'Bekræftet','Pending verification':'Afventer bekræftelse'},
    'ar': {'WordPress':'ووردبريس','Website generation':'إنشاء الموقع','Choose the connected website and domain, then generate or update the website.':'اختر الموقع والنطاق المتصلين، ثم أنشئ الموقع أو حدّثه.','Generating…':'جارٍ الإنشاء…','Generation in progress…':'الإنشاء قيد التنفيذ…','Generate website':'إنشاء الموقع','Website':'الموقع','Select website':'اختر الموقع','Domain':'النطاق','Select domain':'اختر النطاق','No domain available':'لا يوجد نطاق متاح','Verified':'تم التحقق','Pending verification':'التحقق قيد الانتظار'},
    'lb': {'WordPress':'WordPress','Website generation':'Websäit generéieren','Choose the connected website and domain, then generate or update the website.':'Wielt déi verbonne Websäit an den Domaine a generéiert oder aktualiséiert d’Websäit.','Generating…':'Gëtt generéiert…','Generation in progress…':'Generéierung leeft…','Generate website':'Websäit generéieren','Website':'Websäit','Select website':'Websäit auswielen','Domain':'Domain','Select domain':'Domain auswielen','No domain available':'Keen Domaine verfügbar','Verified':'Verifizéiert','Pending verification':'Verifizéierung ofwaarden'},
    'mn': {'WordPress':'WordPress','Website generation':'Вэбсайт үүсгэх','Choose the connected website and domain, then generate or update the website.':'Холбогдсон вэбсайт болон домэйныг сонгоод вэбсайтыг үүсгэх эсвэл шинэчилнэ үү.','Generating…':'Үүсгэж байна…','Generation in progress…':'Үүсгэлт явагдаж байна…','Generate website':'Вэбсайт үүсгэх','Website':'Вэбсайт','Select website':'Вэбсайт сонгох','Domain':'Домэйн','Select domain':'Домэйн сонгох','No domain available':'Домэйн байхгүй','Verified':'Баталгаажсан','Pending verification':'Баталгаажуулалт хүлээгдэж байна'},
    'uk': {'WordPress':'WordPress','Website generation':'Генерація вебсайту','Choose the connected website and domain, then generate or update the website.':'Виберіть підключений вебсайт і домен, а потім створіть або оновіть вебсайт.','Generating…':'Генеруємо…','Generation in progress…':'Генерація триває…','Generate website':'Створити вебсайт','Website':'Вебсайт','Select website':'Виберіть вебсайт','Domain':'Домен','Select domain':'Виберіть домен','No domain available':'Домен недоступний','Verified':'Підтверджено','Pending verification':'Очікує підтвердження'},
    'ru': {'WordPress':'WordPress','Website generation':'Создание сайта','Choose the connected website and domain, then generate or update the website.':'Выберите подключённый сайт и домен, затем создайте или обновите сайт.','Generating…':'Создание…','Generation in progress…':'Создание выполняется…','Generate website':'Создать сайт','Website':'Сайт','Select website':'Выберите сайт','Domain':'Домен','Select domain':'Выберите домен','No domain available':'Нет доступного домена','Verified':'Подтверждён','Pending verification':'Ожидает проверки'},
    'zh-CN': {'WordPress':'WordPress','Website generation':'网站生成','Choose the connected website and domain, then generate or update the website.':'选择已连接的网站和域名，然后生成或更新网站。','Generating…':'正在生成…','Generation in progress…':'生成进行中…','Generate website':'生成网站','Website':'网站','Select website':'选择网站','Domain':'域名','Select domain':'选择域名','No domain available':'没有可用域名','Verified':'已验证','Pending verification':'等待验证'},
}
for language, additions in translations.items():
    path = root / f'{language}.json'
    data = json.loads(path.read_text()) if path.exists() else {}
    data.update(additions)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print(f'updated {len(translations)} locale overrides with {len(next(iter(translations.values())))} portal strings')
